export const config = () => ({
  NODE_ENV: process.env.NODE_ENV,
  PORT: parseInt(process.env.PORT || '', 10),
  DB_CONNECTION_URL: process.env.DB_CONNECTION_URL,
  SECURITY_JWT_SECRET: process.env.SECURITY_JWT_SECRET,
  SECURITY_PASSWORD_SALT_ROUND: process.env.SECURITY_PASSWORD_SALT_ROUND,
  SECURITY_ACCESS_TOKEN_EXPIRED: process.env.SECURITY_ACCESS_TOKEN_EXPIRED,
});
